name: build-test-on-pr
on: [ pull_request, workflow_dispatch ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 'Setup Node.js with pnpm cache'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run -r build:js
      - run: pnpm run test

  build-electron:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 'Setup Node.js with pnpm cache'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run -r --filter "agent-explore^..." build:js # only the dependencies of agent-explore

      - name: Build Electron app
        uses: paneron/action-electron-builder@v1.8.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          package_root: "./packages/agent-explore"
          build_script_name: build-electron
          package_manager: pnpm
